name: Publish NuGet Package

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main

jobs:
  versionize:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.SemVer }}
      sha: ${{ steps.gitversion.outputs.Sha }}
      mmp: ${{ steps.gitversion.outputs.MajorMinorPatch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true

  build:
    runs-on: ubuntu-latest
    name: Update NuGet
    needs: versionize
    steps:
      - uses: actions/checkout@v4

      - run: dotnet build src/DDD.sln -c Release /p:AssemblyVersion=${{needs.versionize.outputs.semver}} /p:FileVersion=${{needs.versionize.outputs.semver}} /p:InformationalVersion=${{needs.versionize.outputs.sha}}
      - run: dotnet test src/DDD.sln
      - run: dotnet pack src/HexMaster.DomainDrivenDesign/HexMaster.DomainDrivenDesign.csproj -c Release -p:AssemblyVersion=${{needs.versionize.outputs.semver}} -p:FileVersion=${{needs.versionize.outputs.semver}} -p:InformationalVersion=${{needs.versionize.outputs.sha}} -p:PackageVersion=${{needs.versionize.outputs.mmp}}
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src/HexMaster.DomainDrivenDesign/bin/Release/*${{needs.versionize.outputs.mmp}}.nupkg

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    name: Deploy NuGet Package
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./package
      - name: Publish
        run: nuget push package/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
