name: Publish NuGet Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Update NuGet 
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet build src/DDD.sln -c Release
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: src/HexMaster.DomainDrivenDesign/bin/Release/*.nupkg